version: "3"

networks:
  web:
    external: false
    
volumes:
  datadrive:
    external: false
  mysql_db:

services:
  seq:
    image: datalust/seq:latest
    deploy:
      resources:
        limits:
          memory: 14G
        reservations:
          memory: 14G
    volumes:
      - ./datadrive:/data
    environment:
      - ACCEPT_EULA=Y
      #- BASE_URI=https://seq.<snip>.com
    ports:
      - "5341:80"
    networks:
      - web
    labels:
      - traefik.backend=seq
      - traefik.frontend.rule=Host:seq.<snip>.com
      - traefik.docker.network=web
      - traefik.port=80
        
  # Database instance
  mysql:
    image: mysql:latest
    volumes:
      - mysql_db:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: mukurueppdb
      MYSQL_USER: mukurueppdbuser
      MYSQL_PASSWORD: userpw